version: '3.5'
services:
  todo-backend:
    container_name: todo-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
  db:
    container_name: todo-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
